###http://geekyplatypus.com/dockerise-your-php-application-with-nginx-and-php7-fpm/
version: '2'
services:
  mysql:
    container_name: local_mysql
    restart: always
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 'zend' # TODO: Change this
      MYSQL_USER: 'root'
      MYSQL_PASS: 'zend'
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - mbot-network
  web:
    container_name: local_nginx
    restart: always
    image: nginx:latest
    ports:
        - "80:80"
    volumes:
        - "./www:/code"
        - "./nginx/site.conf:/etc/nginx/conf.d/default.conf"
        - "./nginx/logs:/var/log/nginx"
    networks:
        - mbot-network
  php:
    container_name: local_php7-fpm
    restart: always
    image: php:fpm
    volumes:
        - "./www:/code"
    ports:
        - "8000:8000"
    networks:
        - mbot-network
networks:
  mbot-network:
      driver: bridge