###http://geekyplatypus.com/dockerise-your-php-application-with-nginx-and-php7-fpm/
version: '2'
services:
  mysql:
    container_name: local_mysql
    restart: always
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: 'zend' # TODO: Change this
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER: 'wordpress'
      MYSQL_PASSWORD: 'wordpress123'
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    networks:
      - lamp-network
  web:
    container_name: local_apache
    restart: always
    image: eboraas/apache
    ports:
      - "80:80"
    volumes:
      - "./apache/logs:/var/log/apache2"
    networks:
      - lamp-network
networks:
  mbot-network:
      driver: bridge